blank_issues_enabled: false
contact_links:
  - name: Hanzo Ingress Discussions
    url: https://github.com/hanzoai/ingress/discussions
    about: If you have a question, or are looking for advice, please post in our GitHub Discussions.
