apiVersion: v1
kind: Service
metadata:
  name: hanzo-ingress
  namespace: lux-system
  labels:
    app: hanzo-ingress
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "lux-ingress"
    service.beta.kubernetes.io/do-loadbalancer-size-unit: "1"
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "true"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    targetPort: web
    protocol: TCP
  - name: https
    port: 443
    targetPort: websecure
    protocol: TCP
  selector:
    app: hanzo-ingress
